# Generated by Django 2.0.9 on 2019-01-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='live_stream_author_id',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Live stream author unique identifier'),
        ),
    ]
